// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxiAFXVJXLyqNuNuwseaHgQDxAIfHXImM',
    appId: '1:980573689100:web:98cf67914d27c12b556529',
    messagingSenderId: '980573689100',
    projectId: 'maximagri',
    authDomain: 'maximagri.firebaseapp.com',
    storageBucket: 'maximagri.appspot.com',
    measurementId: 'G-04BN90YJK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcBDT0nFHR2KKIdf4DwKC2sivJPYWjrqY',
    appId: '1:980573689100:android:c7c99a4d16753c13556529',
    messagingSenderId: '980573689100',
    projectId: 'maximagri',
    storageBucket: 'maximagri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYoxQiNsXn6Tsgd8WzDHzAQAhqAl8iLpQ',
    appId: '1:980573689100:ios:5d2d3df377c70ec9556529',
    messagingSenderId: '980573689100',
    projectId: 'maximagri',
    storageBucket: 'maximagri.appspot.com',
    iosClientId: '980573689100-jiumra1q0puqmjcfk1tfgllg02s1fnv0.apps.googleusercontent.com',
    iosBundleId: 'com.maximagri.maximagri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYoxQiNsXn6Tsgd8WzDHzAQAhqAl8iLpQ',
    appId: '1:980573689100:ios:5d2d3df377c70ec9556529',
    messagingSenderId: '980573689100',
    projectId: 'maximagri',
    storageBucket: 'maximagri.appspot.com',
    iosClientId: '980573689100-jiumra1q0puqmjcfk1tfgllg02s1fnv0.apps.googleusercontent.com',
    iosBundleId: 'com.maximagri.maximagri',
  );
}
